name: Telegram Bot

on:
  push:
    branches:
      - main
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-telegram-bot
    - name: Send message to Telegram
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        # Define el texto de entrada que se utilizará para generar una respuesta de ChatGPT.
        input_text = "Hola, ¿cómo estás?"

        # Envía una solicitud HTTP a la API de OpenAI para obtener una respuesta de ChatGPT.
        response = requests.post(
            "https://api.openai.com/v1/completions",
            headers={
                "Authorization": f"Bearer {OPENAI_API_KEY}",
                "Content-Type": "application/json"
            },
            json={
                "prompt": input_text,
                "temperature": 0.5,
                "max_tokens": 50,
                "top_p": 1,
                "frequency_penalty": 0,
                "presence_penalty": 0
            }
        )

        # Extrae la respuesta de la API de OpenAI y la envía a través de la API de Telegram.
        response_text = response.json()["choices"][0]["text"]
        bot = telegram.Bot(token=TELEGRAM_BOT_TOKEN)
        bot.send_message(chat_id=TELEGRAM_CHAT_ID, text=response_text)
