name: Medición de velocidad de página y envío de resultado a WhatsApp
on:
  push:
    branches:
      - main

jobs:
  measure-speed-and-send-result:
    runs-on: ubuntu-latest
    steps:
      - name: Medir velocidad de página
        run: |
          # Comandos para medir velocidad de página y guardar resultado en archivo speed.txt
          # Se recomienda utilizar una herramienta de prueba de velocidad de página web como Lighthouse o PageSpeed Insights.
          # Ejemplo de cómo guardar el resultado en un archivo speed.txt:
          echo "Velocidad de página: 80" > speed.txt

      - name: Enviar resultado a WhatsApp
        uses: twilio-labs/action-send-whatsapp@v3
        with:
          account_sid: ${{ secrets.TWILIO_ACCOUNT_SID }}
          auth_token: ${{ secrets.TWILIO_AUTH_TOKEN }}
          from: 'whatsapp:+14155238886' # número de teléfono de Twilio para enviar mensajes de WhatsApp
          to: 'whatsapp:+51922656684' # número de teléfono del destinatario de WhatsApp
          body: "La velocidad de la página es $(cat speed.txt)"
