name: Lighthouse Performance Test

on: [push]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install

      - name: Run Lighthouse test
        run: |
          npx lighthouse https://www.mariaalmenara.pe --output json --output-path=./report.json
