name: Medición de velocidad de carga de página web
on:
  push:
    branches: [ main ]
jobs:
  speed-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Instalar dependencias
        run: |
          npm install -g psi
      - name: Análisis de velocidad de carga
        run: |
          psi https://www.mariaalmenara.pe --nokey --strategy=mobile --threshold=90
